/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BasicRiskpool } from "./BasicRiskpool";
export type { Component } from "./Component";
export type { IAccess } from "./IAccess";
export type { IBundle } from "./IBundle";
export type { IBundleToken } from "./IBundleToken";
export type { IComponent } from "./IComponent";
export type { IComponentEvents } from "./IComponentEvents";
export type { IComponentOwnerService } from "./IComponentOwnerService";
export type { ICoreProxy } from "./ICoreProxy";
export type { IInstanceOperatorService } from "./IInstanceOperatorService";
export type { IInstanceService } from "./IInstanceService";
export type { ILicense } from "./ILicense";
export type { IOracle } from "./IOracle";
export type { IOracleService } from "./IOracleService";
export type { IPolicy } from "./IPolicy";
export type { IPool } from "./IPool";
export type { IProduct } from "./IProduct";
export type { IProductService } from "./IProductService";
export type { IQuery } from "./IQuery";
export type { IRegistry } from "./IRegistry";
export type { IRiskpool } from "./IRiskpool";
export type { IRiskpoolService } from "./IRiskpoolService";
export type { ITreasury } from "./ITreasury";
export type { Oracle } from "./Oracle";
export type { Product } from "./Product";
export type { Riskpool } from "./Riskpool";
