/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface TestRegistryCompromisedControllerInterface
  extends utils.Interface {
  functions: {
    "POLICY()": FunctionFragment;
    "QUERY()": FunctionFragment;
    "contracts(bytes32)": FunctionFragment;
    "getContract(bytes32)": FunctionFragment;
    "upgradeToV2(address,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "POLICY"
      | "QUERY"
      | "contracts"
      | "getContract"
      | "upgradeToV2"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "POLICY", values?: undefined): string;
  encodeFunctionData(functionFragment: "QUERY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "contracts",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getContract",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToV2",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "POLICY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "QUERY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "contracts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToV2",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TestRegistryCompromisedController extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestRegistryCompromisedControllerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    POLICY(overrides?: CallOverrides): Promise<[string]>;

    QUERY(overrides?: CallOverrides): Promise<[string]>;

    contracts(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getContract(
      contractName: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string] & { moduleAddress: string }>;

    upgradeToV2(
      compromisedPolicyModuleAddress: PromiseOrValue<string>,
      originalQueryModuleAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  POLICY(overrides?: CallOverrides): Promise<string>;

  QUERY(overrides?: CallOverrides): Promise<string>;

  contracts(
    arg0: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getContract(
    contractName: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  upgradeToV2(
    compromisedPolicyModuleAddress: PromiseOrValue<string>,
    originalQueryModuleAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    POLICY(overrides?: CallOverrides): Promise<string>;

    QUERY(overrides?: CallOverrides): Promise<string>;

    contracts(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getContract(
      contractName: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    upgradeToV2(
      compromisedPolicyModuleAddress: PromiseOrValue<string>,
      originalQueryModuleAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    POLICY(overrides?: CallOverrides): Promise<BigNumber>;

    QUERY(overrides?: CallOverrides): Promise<BigNumber>;

    contracts(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getContract(
      contractName: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    upgradeToV2(
      compromisedPolicyModuleAddress: PromiseOrValue<string>,
      originalQueryModuleAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    POLICY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    QUERY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    contracts(
      arg0: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getContract(
      contractName: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    upgradeToV2(
      compromisedPolicyModuleAddress: PromiseOrValue<string>,
      originalQueryModuleAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
